### ISSUE TITLE
Parse the tables into a better format

### ISSUE THREAD

**Issue by gdunstone** [KenBehren/exposure-locations#2]
the .txt that the script generates is not particularly diff or user friendly. Tomorrow I can submit a PR to parse the tables into csv or an excel spreadsheet if you like.

**Comment by KenBehren** [comment]
Agree, the diffs could be cleaner. PRs welcome!

I’ve been looking at the changes coming through and there are lots of minor formatting changes that need to be filtered out as well:

- Dates changed from `12 August` to `Thursday 12 August` to `Thursday, 12 August`
- Times are inconsistently separated with `.`, `:` and even `”` (and the subsequent edits to fix them up)
- `12:00pm` sometimes shown as `12 noon`
- The first column that shows `New` and `Updated` can be ignored for a diff
- Place names and addresses get clarified Eg `Civic -> Canberra City`

In the absence of a structured feed from data.act.gov.au, I think putting effort into a cleansed JSON version of locations.txt would be useful. Thoughts?

**Comment by gdunstone** [comment]
I was going to do csv because its easy(ish) for people to read and load into excel and sort, but once its parsed into python it should be easy to output json also.

I thought about the problem with the times also, a large proportion of my job revolves around datetimes and parsing them. I was thinking of adding an extra column or two and using python-dateutil to parse them.

**Comment by KenBehren** [comment]
@gdunstone thank you for your contribution! I’ve merged it and made a few additional tweaks.
