### ISSUE TITLE
Alternative data source you might like to consider using

### ISSUE THREAD

**Issue by FrakGart** [KenBehren/exposure-locations#3]
They appear to also be putting the exposure sites into an ArcGIS database. You could also pull these:

https://services1.arcgis.com/E5n4f1VY84i0xSjy/ArcGIS/rest/services/ACT_Exposure_Sites/FeatureServer/0/query?where=OBJECTID%3E0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson

**Comment by KenBehren** [comment]
Wow, thanks for sharing. How did you find this?

**Comment by FrakGart** [comment]
I wanted to make my own map, so I was looking at the page source and noticed that they have a map embedded currently but the link is commented out.  If you go to the map:

https://actgov.maps.arcgis.com/apps/instant/media/index.html?appid=511888ad746c40e6847b942db37f9ec9

you can find where they are pulling the data for the map.
